INSERT INTO roles (id, name, permissions)
VALUES
  (1, 'admin',  ARRAY['create','read','update','delete','superuser']),
  (2, 'guest',  ARRAY['read'])
ON CONFLICT DO NOTHING;
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Alabama', 'AL', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Alaska', 'AK',1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Arizona', 'AZ', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Arkansas', 'AR', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('California', 'CA', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Colorado', 'CO', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Connecticut', 'CT', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Delaware', 'DE', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Florida', 'FL', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Georgia', 'GA', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Hawaii', 'HI', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Idaho', 'ID', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Illinois', 'IL', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Indiana', 'IN', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Iowa', 'IA', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Kansas', 'KS', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Kentucky', 'KY', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Louisiana', 'LA', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Maine', 'ME', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Maryland', 'MD', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Massachusetts', 'MA', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Michigan', 'MI', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Minnesota', 'MN', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Mississippi', 'MS', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Missouri', 'MO', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Montana', 'MT', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Nebraska', 'NE', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Nevada', 'NV', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('New Hampshire', 'NH', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('New Jersey', 'NJ', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('New Mexico', 'NM', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('New York', 'NY', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('North Carolina', 'NC', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('North Dakota', 'ND', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Ohio', 'OH', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Oklahoma', 'OK', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Oregon', 'OR', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Pennsylvania', 'PA', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Rhode Island', 'RI', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('South Carolina', 'SC', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('South Dakota', 'SD', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Tennessee', 'TN', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Texas', 'TX', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Utah', 'UT', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Vermont', 'VT', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Virginia', 'VA', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Washington', 'WA', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('West Virginia', 'WV', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Wisconsin', 'WI', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Wyoming', 'WY', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('American Samoa', 'AS', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Guam', 'GU', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Northern Mariana Islands', 'MP', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Puerto Rico', 'PR', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('U.S. Virgin Islands', 'VI', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('District of Columbia', 'DC', 1, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Alberta', 'AB', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('British Columbia', 'BC', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Manitoba', 'MB', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('New Brunswick', 'NB', 2, TRUE, NOW(), NOW()),
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Newfoundland and Labrador', 'NL', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Nova Scotia', 'NS', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Ontario', 'ON', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Prince Edward Island', 'PE', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Quebec', 'QC', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Saskatchewan', 'SK', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Northwest Territories', 'NT', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Nunavut', 'NU', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Yukon', 'YT', 2, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Aguascalientes', 'AG', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Baja California', 'BC', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Baja California Sur', 'BS', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Campeche', 'CM', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Chiapas', 'CS', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Chihuahua', 'CH', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Coahuila', 'CO', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Colima', 'CL', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Durango', 'DG', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Guanajuato', 'GT', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Guerrero', 'GR', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Hidalgo', 'HG', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Jalisco', 'JA', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Mexico State', 'EM', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Mexico City', 'DF', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Michoacán', 'MI', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Morelos', 'MO', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Nayarit', 'NA', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Nuevo León', 'NL', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Oaxaca', 'OA', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Puebla', 'PU', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Querétaro', 'QE', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Quintana Roo', 'QR', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('San Luis Potosí', 'SL', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Sinaloa', 'SI', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Sonora', 'SO', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Tabasco', 'TB', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Tamaulipas', 'TM', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Tlaxcala', 'TL', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Veracruz', 'VE', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Yucatán', 'YU', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Zacatecas', 'ZA', 3, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Acre', 'AC', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Alagoas', 'AL', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Amapá', 'AP', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Amazonas', 'AM', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Bahia', 'BA', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Ceará', 'CE', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Distrito Federal', 'DF', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Espírito Santo', 'ES', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Goiás', 'GO', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Maranhão', 'MA', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Mato Grosso', 'MT', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Mato Grosso do Sul', 'MS', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Minas Gerais', 'MG', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Pará', 'PA', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Paraíba', 'PB', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Paraná', 'PR', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Pernambuco', 'PE', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Piauí', 'PI', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Rio de Janeiro', 'RJ', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Rio Grande do Norte', 'RN', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Rio Grande do Sul', 'RS', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Rondônia', 'RO', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Roraima', 'RR', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Santa Catarina', 'SC', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('São Paulo', 'SP', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Sergipe', 'SE', 4, TRUE, NOW(), NOW());
INSERT INTO states_provinces (name, code, country_id, is_active, created_at, updated_at) VALUES ('Tocantins', 'TO', 4, TRUE, NOW(), NOW());

